
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-6pm-4
owner: ucsb-cs156-s23
repo_name: team03-s23-6pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjgxNTkzMTk4","is_bot":false,"login":"jessicahsy","name":"Jessica Ho"},"headRefName":"jessicah-music-backend","number":21,"title":"Jessicah music backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-4/pull/21"},{"author":{"id":"MDQ6VXNlcjcwMTEzOTg3","is_bot":false,"login":"jessica-lieu","name":""},"headRefName":"JessicaL-ApartmentFrontend","number":20,"title":"jl - added ApartmentFrontend","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-4/pull/20"},{"author":{"id":"MDQ6VXNlcjc3NjkzMzkz","is_bot":false,"login":"ykeung","name":"Yuki Keung"},"headRefName":"YukiK-RestaurantFrontendCrud","number":19,"title":"Bring over frontend crud files for Restaurant from team01","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-4/pull/19"},{"author":{"id":"MDQ6VXNlcjgxMzQxODE5","is_bot":false,"login":"kshitij0407","name":"Kshitij Agarwal"},"headRefName":"KrishA-Team03","number":15,"title":"Added all frontend files from team01 into team03","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-4/pull/15"}]
