
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-6pm-4
owner: ucsb-cs156-s23
repo_name: team03-s23-6pm-4
pull_requests: [{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-ApartmentUseJavaBackend","number":30,"title":"Jacob w apartment use java backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-4/pull/30"},{"author":{"id":"MDQ6VXNlcjgxMzQxODE5","is_bot":false,"login":"kshitij0407","name":"Kshitij Agarwal"},"headRefName":"KrishA-Team03","number":15,"title":"Added all frontend files from team01 into team03","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-4/pull/15"}]
